apiVersion: v1
kind: LimitRange
metadata:
  name: hello
spec:
  limits: 
    - default: #maximum of resource until die
        cpu: "200m"
        memory: "256Mi"
      defaultRequest: #minimum requested to run
        cpu: "100m"
        memory: "128Mi"      
      type: Container