apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: #Deployment annotatios
    kubernetes.io/change-cause: "Update to blue kuard"
  #label
  name: kuard
spec:
  selector:
    matchLabels:
      run: kuard
  replicas: 10
  template:
    metadata:
      annotations: #Pod annotations
        kubernetes.io/change-cause: "Update to blue kuard"
      labels:
        run: kuard
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:blue