apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo

spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
        run: demo
    spec:
      containers:
        - name: demo
          image: cloudnatived/demo:hello
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP