apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    app: demo
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8888
  selector: #Send request to pods with label app: demo
    app: demo
  type: ClusterIP
