apiVersion: apps/v1
kind: Deployment
metadata: #Deployment metadata
  name: alpaca
  labels:
    ver: "2"
    app: alpaca
    env: test
spec:
  selector:
    matchLabels:
      app: alpaca-test
  replicas: 3
  template:
    metadata: #Pod metadata
      labels:
        ver: "2"
        app: alpaca-test
        env: test
    spec: 
      containers:
        - name: kuard
          image: gcr.io/kuar-demo/kuard-amd64:blue
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
