apiVersion: v1
kind: Pod
metadata:
  name: demo

#MUST
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredSuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: "failure-domain.brta.kubernetes.io/zone"
              operator: In
              values: ["us-central1-a"]

#SHOULD + weight
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredSuringExecution:
      - weight: 10
        preference:
          - matchExpressions:
            - key: "failure-domain.brta.kubernetes.io/zone"
              operator: In
              values: ["us-central1-a"]

      - weight: 100
        preference:
          - matchExpressions:
            - key: "failure-domain.brta.kubernetes.io/zone"
              operator: In
              values: ["us-central1-b"]