apiVersion: v1
kind: Pod
metadata:
  name: demo
  
spec:
  volumes:
    - name: cache-volume
      emptyDir: {}
  containers:
    - name: demo
      image: cloudnatived/demo:hello
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
      ports:
        - containerPort: 8888
          name: http
          protocol: TCP
      volumeMounts:
        - name: cache-volume
          mountPath: /cache